# Site Settings
title: Betta Dev Indonesia
email: bettadevindonesia@gmail.com
description: >
  Small Blog to Comunity
baseurl: ""
url: "http://localhost:4000"
twitter_username: trojan302
github_username:  trojan302
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM